server:
  port: ${SERVER_PORT:8082}

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/orthodonticBill/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/orthodonticBill/api-docs/swagger-ui.html

spring:
  application:
    name: ${SERVICE_NAME:OrthodonticBillService}
  profiles:
    active: ${ACTIVE_PROFILE:desktop-dev} #nitro-dev or desktop-dev or macc-prod or nitro-kub-prod
